version: '3.8'

services:
  frontend:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - alectrion-network
    ports:
      - 3000:3000
    command: sh -c "npm install && npm i -D esbuild && npm run build && npm run start"

networks:
  alectrion-network:
    external: true