name: CodeAnalysis
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test and coverage
        run: yarn test
      - name: SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}